# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3


class Ui_MainRegister(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 0, 231, 111))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 240, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 240, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 320, 121, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 100, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 170, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 100, 91, 21))
        self.label_7.setObjectName("label_7")
        self.fullname = QtWidgets.QLineEdit(self.centralwidget)
        self.fullname.setGeometry(QtCore.QRect(110, 120, 221, 31))
        self.fullname.setObjectName("fullname")
        self.phone = QtWidgets.QLineEdit(self.centralwidget)
        self.phone.setGeometry(QtCore.QRect(510, 120, 201, 31))
        self.phone.setObjectName("phone")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(110, 190, 221, 31))
        self.email.setObjectName("email")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(110, 260, 221, 31))
        self.username.setObjectName("username")
        self.pasword = QtWidgets.QLineEdit(self.centralwidget)
        self.pasword.setGeometry(QtCore.QRect(510, 260, 191, 31))
        self.pasword.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pasword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pasword.setPlaceholderText("")
        self.pasword.setObjectName("pasword")
        self.passwordagain = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordagain.setGeometry(QtCore.QRect(510, 340, 191, 31))
        self.passwordagain.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordagain.setObjectName("passwordagain")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(540, 40, 93, 28))
        self.submit.setObjectName("submit")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(680, 40, 93, 28))
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.back.clicked.connect(lambda: self.backformlogin(MainWindow))
        self.submit.clicked.connect(self.registerbackend)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ff0000;\">Register</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_3.setText(_translate("MainWindow", "Passwword"))
        self.label_4.setText(_translate("MainWindow", "Confirm password"))
        self.label_5.setText(_translate("MainWindow", "Full name"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.label_7.setText(_translate("MainWindow", "Phone number"))
        self.submit.setText(_translate("MainWindow", "submit"))
        self.back.setText(_translate("MainWindow", "back"))
    def backformlogin(self, MainWindow):
        MainWindow.hide()
    def checkuser(self):
        self.conn = sqlite3.connect("E:/bc/ktpython.db")
        query = "SELECT user FROM admin"
        self.curor = self.conn.execute(query)
        self.row = self.curor.fetchall()
        #print(self.row)
        return self.row.pop(0)
        self.conn.close()
    def registerbackend(self):
        self.checkuser()
        username = self.username.text()
        password = self.pasword.text()
        passwordagain = self.passwordagain.text()
        fullname = self.fullname.text()
        email = self.email.text()
        txtphonenumber = self.phone.text()
        if username == '' or password == '' or fullname == '' or email == '' or txtphonenumber == '':
            self.eror = QtWidgets.QErrorMessage()
            self.eror.showMessage("Vui lòng điền đầy đủ thông tin!")
        elif txtphonenumber.isdecimal() == False:
            self.eror = QtWidgets.QErrorMessage()
            self.eror.showMessage("Số điện thoại bạn nhập chưa chính xác!")
        elif (username,) in self.row:
            self.eror = QtWidgets.QErrorMessage()
            self.eror.showMessage("Tài khoản bạn đang đăng kí đã tồn tại")
        else:
            if password == passwordagain:
                self.conn = sqlite3.connect("E:/bc/ktpython.db")
                query = "INSERT INTO admin(user,password,name,phonenumber,email) VALUES (?,?,?,?,?)"
                data = (username,password,fullname,txtphonenumber,email)
                self.conn.execute(query,data)
                self.conn.commit()
                self.conn.close()
                self.msg = QMessageBox()
                self.msg.setIcon(QMessageBox.Information)
                self.msg.setText("Tài khoản được đăng kí thành công")
                self.msg.setWindowTitle("Đăng kí")
                self.msg.show()
            else:
                self.eror = QtWidgets.QErrorMessage()
                self.eror.showMessage("Xác nhận lại mật khẩu chưa đúng!")
       #

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainRegister()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
